.TH "SNAPM" "8" "Dec 18 2025" "Linux" "MAINTENANCE COMMANDS"
.\" Compatibility for older groff (1.22.x) lacking EX/EE
.ie d EX \{\
.\}
.el \{\
.de EX
.  nf
.  RS
..
.de EE
.  RE
.  fi
..
.\}
.
.\" URL macro fallbacks for man2html compatibility (and groff without man-ext)
.\" Define UR and UE independently so we don't assume both exist.
.if !d UR \{\
.de UR
\\$2 \(la\\$1\(ra
..
.\}
.if !d UE \{\
.de UE
.  br
..
.\}
.
.de ARG_GLOBAL
.  RI [global_args] " "\c
..
.
.de ARG_SNAPSET_TYPE
.  RI snapset " "\c
..
.
.de ARG_SNAPSET_COMMANDS
.  RI create | create-scheduled | delete | rename | revert | resize " "\c
.  RI | split | prune | activate | deactivate | diff | diffreport 
.  RI | autoactivate | list | show " "\c
.  RI | mount | umount | exec | shell
..
.
.de ARG_SNAPSHOT_TYPE
.  RI snapshot " "\c
..
.
.de ARG_SNAPSHOT_COMMANDS
.  RI activate | deactivate | autoactivate | list | show
..
.de ARG_PLUGIN_TYPE
.  RI plugin " "\c
..
.de ARG_PLUGIN_COMMANDS
.  RI list " "\c
..
.
.de ARG_SCHEDULE_TYPE
.  RI schedule " "\c
..
.de ARG_SCHEDULE_COMMANDS
.  RI create | delete | edit | enable | disable | list | show | gc
..
.
.de ARG_NAME
.  RI name " "\c
..
.
.de ARG_COMMAND
.  RI command " "\c
..
.
.de ARG_NAME_OR_UUID
.  RI [ name | UUID ] " "\c
.  RB [ -n | --name\ \c
.  IR name ] " "\c
.  RB [ -u | --uuid\ \c
.  IR UUID ] " "\c
..
.
.de ARG_SNAPSHOT_NAME_OR_UUID
.  RB [ -N | --snapshot-name\ \c
.  IR name ] " "\c
.  RB [ -U | --snapshot-uuid\ \c
.  IR UUID ] " "\c
..
.
.de ARGS_REPORT_OPTS
.  RB [ --name-prefixes | --nameprefixes ] " "\c
.  RB [ --no-headings | --noheadings ] " "\c
.  RB [ -o | --options\ \c
.  IR fields ] " "\c
.  RB [ -O | --sort\ \c
.  IR sort_fields ] " "\c
.  RB [ --rows | --json ] " "\c
.  RB [ --separator\ \c
.  IR separator ] " "\c
..
.
.SH NAME
.
snapm \- Linux Snapshot Manager
.
.SH SYNOPSIS
.
.SS Command Types
.B snapm
.de CMD_SNAPSET_COMMAND
.  ARG_GLOBAL
.  ARG_SNAPSET_TYPE
.  ARG_SNAPSET_COMMANDS
..
.CMD_SNAPSET_COMMAND
.br
.
.B snapm
.de CMD_SNAPSHOT_COMMAND
.  ARG_GLOBAL
.  ARG_SNAPSHOT_TYPE
.  ARG_SNAPSHOT_COMMANDS
..
.CMD_SNAPSHOT_COMMAND
.br
.
.B snapm
.de CMD_PLUGIN_COMMAND
.  ARG_GLOBAL
.  ARG_PLUGIN_TYPE
.  ARG_PLUGIN_COMMANDS
..
.CMD_PLUGIN_COMMAND
.br
.
.B snapm
.de CMD_SCHEDULE_COMMAND
.  ARG_GLOBAL
.  ARG_SCHEDULE_TYPE
.  ARG_SCHEDULE_COMMANDS
..
.CMD_SCHEDULE_COMMAND
.br
.PP
.SS Subcommands
.B snapm
.de CMD_SNAPSET_CREATE
.  B snapset
.  B create
.  RB [-b | --bootable] " "\c
.  RB [-r | --revert] " "\c
.  RI [-s | --size-policy\ \c
.  IR policy] " "\c
.  RB [-a | --autoindex] " "\c
.  RB [--json] " "\c
.  IR name " "\c
.  RI source[size_policy] ... " "\c
..
.CMD_SNAPSET_CREATE
.br
.
.B snapm
.de CMD_SNAPSET_CREATE_SCHEDULED
.  B snapset
.  B create-scheduled
.  RB -c | --config\ \c
.  IR schedule_name " "\c
.  RB [--json] " "\c
..
.CMD_SNAPSET_CREATE_SCHEDULED
.br
.
.B snapm
.de CMD_SNAPSET_DELETE
.  B snapset
.  B delete
.  ARG_NAME_OR_UUID
..
.CMD_SNAPSET_DELETE
.br
.B snapm
.de CMD_SNAPSET_DIFF
.  B snapset
.  B diff
.  RB [ -o | --output-format\ \c
.  IR format ] " "\c
.  RB [ -P | --pretty ] " "\c
.  RB [ -D | --desc\ \c
.  IR mode ] " "\c
.  RB [ -t | --ignore-timestamps ] " "\c
.  RB [ -p | --ignore-permissions ] " "\c
.  RB [ -w | --ignore-ownership ] " "\c
.  RB [ -c | --content-only ] " "\c
.  RB [ -C | --no-content-diff ] " "\c
.  RB [ -f | --file-types ] " "\c
.  RB [ -F | --follow-symlinks ] " "\c
.  RB [ -m | --max-file-size\ \c
.  IR size ] " "\c
.  RB [ -z | --max-diff-size\ \c
.  IR size ] " "\c
.  RB [ -H | --max-hash-size\ \c
.  IR size ] " "\c
.  RB [ -i | --include-pattern\ \c
.  IR pattern ] " "\c
.  RB [ -x | --exclude-pattern\ \c
.  IR pattern ] " "\c
.  RB [ -s | --start-path\ \c
.  IR path ] " "\c
.  RB [ --stat ] " "\c
.  RB [ -q | --quiet ] " "\c
.  RB [ --color\ \c
.  IR mode ] " "\c
.  RB [ -M | --cache-mode\ \c
.  IR cache_mode ] " "\c
.  RB [ --cache-expires\ \c
.  IR expire_secs ] " "\c
.  IR from " "\c
.  IR to " "\c
..
.CMD_SNAPSET_DIFF
.br
.
.B snapm
.de CMD_SNAPSET_DIFFREPORT
.  B snapset
.  B diffreport
.  ARGS_REPORT_OPTS
.  RB [ -t | --ignore-timestamps ] " "\c
.  RB [ -p | --ignore-permissions ] " "\c
.  RB [ -w | --ignore-ownership ] " "\c
.  RB [ -c | --content-only ] " "\c
.  RB [ -C | --no-content-diff ] " "\c
.  RB [ -f | --file-types ] " "\c
.  RB [ -F | --follow-symlinks ] " "\c
.  RB [ -m | --max-file-size\ \c
.  IR size ] " "\c
.  RB [ -z | --max-diff-size\ \c
.  IR size ] " "\c
.  RB [ -H | --max-hash-size\ \c
.  IR size ] " "\c
.  RB [ -i | --include-pattern\ \c
.  IR pattern ] " "\c
.  RB [ -x | --exclude-pattern\ \c
.  IR pattern ] " "\c
.  RB [ -s | --start-path\ \c
.  IR path ] " "\c
.  RB [ -q | --quiet ] " "\c
.  RB [ --color\ \c
.  IR mode ] " "\c
.  RB [ -M | --cache-mode\ \c
.  IR cache_mode ] " "\c
.  RB [ --cache-expires\ \c
.  IR expire_secs ] " "\c
.  IR from " "\c
.  IR to " "\c
..
.CMD_SNAPSET_DIFFREPORT
.
.B snapm
.de CMD_SNAPSET_RENAME
.  B snapset
.  B rename
.  IR old_name " "\c
.  IR new_name " "\c
..
.CMD_SNAPSET_RENAME
.br
.
.B snapm
.de CMD_SNAPSET_REVERT
.  B snapset
.  B revert
.  ARG_NAME_OR_UUID
..
.CMD_SNAPSET_REVERT
.br
.
.B snapm
.de CMD_SNAPSET_RESIZE
.  B snapset
.  B resize
.  ARG_NAME_OR_UUID
.  RB [ -s | --size-policy\ \c
.  IR policy] " "\c
.  RI [ source[size_policy] ... ] " "\c
..
.CMD_SNAPSET_RESIZE
.br
.
.B snapm
.de CMD_SNAPSET_SPLIT
.  B snapset
.  B split
.  IR name " "\c
.  IR new_name " "\c
.  IR source ... " "\c
..
.CMD_SNAPSET_SPLIT
.br
.
.B snapm
.de CMD_SNAPSET_PRUNE
.  B snapset
.  B prune
.  IR name " "\c
.  IR source ... " "\c
..
.CMD_SNAPSET_PRUNE
.br
.
.B snapm
.de CMD_SNAPSET_ACTIVATE
.  B snapset
.  B activate
.  ARG_NAME_OR_UUID
..
.CMD_SNAPSET_ACTIVATE
.br
.
.B snapm
.de CMD_SNAPSET_DEACTIVATE
.  B snapset
.  B deactivate
.  ARG_NAME_OR_UUID
..
.CMD_SNAPSET_DEACTIVATE
.br
.
.B snapm
.de CMD_SNAPSET_AUTOACTIVATE
.  B snapset
.  B autoactivate
.  RB --yes | --no " "\c
.  ARG_NAME_OR_UUID
..
.CMD_SNAPSET_AUTOACTIVATE
.br
.
.B snapm
.de CMD_SNAPSET_LIST
.  B snapset
.  B list
.  ARG_NAME_OR_UUID
.  ARGS_REPORT_OPTS
..
.CMD_SNAPSET_LIST
.br
.
.B snapm
.de CMD_SNAPSET_SHOW
.  B snapset
.  B show
.  ARG_NAME_OR_UUID
.  RB [ --members ] " "\c
.  RB [ --json ] " "\c
..
.CMD_SNAPSET_SHOW
.br
.
.de CMD_SNAPSET_MOUNT
.  B snapset
.  B mount
.  ARG_NAME
..
.CMD_SNAPSET_MOUNT
.br
.
.de CMD_SNAPSET_UMOUNT
.  B snapset
.  B umount
.  ARG_NAME
..
.CMD_SNAPSET_UMOUNT
.br
.
.de CMD_SNAPSET_EXEC
.  B snapset
.  B exec
.  ARG_NAME
.  ARG_COMMAND
..
.CMD_SNAPSET_EXEC
.br
.
.de CMD_SNAPSET_SHELL
.  B snapset
.  B shell
.  ARG_NAME
..
.CMD_SNAPSET_SHELL
.PP
.
.B snapm
.de CMD_SNAPSHOT_ACTIVATE
.  B snapshot
.  B activate
.  ARG_NAME_OR_UUID
.  ARG_SNAPSHOT_NAME_OR_UUID
..
.CMD_SNAPSHOT_ACTIVATE
.br
.
.B snapm
.de CMD_SNAPSHOT_DEACTIVATE
.  B snapshot
.  B deactivate
.  ARG_NAME_OR_UUID
.  ARG_SNAPSHOT_NAME_OR_UUID
..
.CMD_SNAPSHOT_DEACTIVATE
.br
.
.B snapm
.de CMD_SNAPSHOT_AUTOACTIVATE
.  B snapshot
.  B autoactivate
.  RB --yes | --no " "\c
.  ARG_NAME_OR_UUID
.  ARG_SNAPSHOT_NAME_OR_UUID
..
.CMD_SNAPSHOT_AUTOACTIVATE
.br
.
.B snapm
.de CMD_SNAPSHOT_LIST
.  B snapshot
.  B list
.  ARG_NAME_OR_UUID
.  ARG_SNAPSHOT_NAME_OR_UUID
.  ARGS_REPORT_OPTS
..
.CMD_SNAPSHOT_LIST
.br
.
.B snapm
.de CMD_SNAPSHOT_SHOW
.  B snapshot
.  B show
.  ARG_NAME_OR_UUID
.  ARG_SNAPSHOT_NAME_OR_UUID
.  RB [--json] " "\c
..
.CMD_SNAPSHOT_SHOW
.br
.PP
.
.B snapm
.de CMD_PLUGIN_LIST
.  B plugin
.  B list
.  ARGS_REPORT_OPTS
..
.CMD_PLUGIN_LIST
.br
.PP
.
.B snapm
.de CMD_SCHEDULE_CREATE
.  B schedule
.  B create
.  BR  -p | --policy-type\ \c
.  IR policy_type " "\c
.  RB [ -b | --bootable] " "\c
.  RB [ -C | --calendarspec\ \c
.  IR calendarspec] " "\c
.  RB [ -r | --revert] " "\c
.  RB [ -s | --size-policy\ \c
.  IR policy] " "\c
.  RB [ --keep-count\ \c
.  IR count ] " "\c
.  RB [ --keep-years\ \c
.  IR years ] " "\c
.  RB [ --keep-months\ \c
.  IR months ] " "\c
.  RB [ --keep-weeks\ \c
.  IR weeks ] " "\c
.  RB [ --keep-days\ \c
.  IR days ] " "\c
.  RB [ --keep-yearly\ \c
.  IR yearly ] " "\c
.  RB [ --keep-quarterly\ \c
.  IR quarterly ] " "\c
.  RB [ --keep-monthly\ \c
.  IR monthly ] " "\c
.  RB [ --keep-weekly\ \c
.  IR weekly ] " "\c
.  RB [ --keep-daily\ \c
.  IR daily ] " "\c
.  RB [ --keep-hourly\ \c
.  IR hourly ] " "\c
.  IR schedule_name " "\c
.  RI source[size_policy] ... " "\c
..
.CMD_SCHEDULE_CREATE
.br
.
.B snapm
.de CMD_SCHEDULE_DELETE
.  B schedule
.  B delete
.  IR schedule_name " "\c
..
.CMD_SCHEDULE_DELETE
.br
.
.B snapm
.de CMD_SCHEDULE_EDIT
.  B schedule
.  B edit
.  RB [ -p | --policy-type\ \c
.  IR policy_type ] " "\c
.  RB [ -b | --bootable] " "\c
.  RB [ -C | --calendarspec\ \c
.  IR calendarspec] " "\c
.  RB [ -r | --revert] " "\c
.  RB [ -s | --size-policy\ \c
.  IR policy] " "\c
.  RB [ --keep-count\ \c
.  IR count ] " "\c
.  RB [ --keep-years\ \c
.  IR years ] " "\c
.  RB [ --keep-months\ \c
.  IR months ] " "\c
.  RB [ --keep-weeks\ \c
.  IR weeks ] " "\c
.  RB [ --keep-days\ \c
.  IR days ] " "\c
.  RB [ --keep-yearly\ \c
.  IR yearly ] " "\c
.  RB [ --keep-quarterly\ \c
.  IR quarterly ] " "\c
.  RB [ --keep-monthly\ \c
.  IR monthly ] " "\c
.  RB [ --keep-weekly\ \c
.  IR weekly ] " "\c
.  RB [ --keep-daily\ \c
.  IR daily ] " "\c
.  RB [ --keep-hourly\ \c
.  IR hourly ] " "\c
.  IR schedule_name " "\c
.  RI [ source[size_policy] ... ] " "\c
..
.CMD_SCHEDULE_EDIT
.br
.
.B snapm
.de CMD_SCHEDULE_ENABLE
.  B schedule
.  B enable
.  IR schedule_name " "\c
.  RB [--start] " "\c
..
.CMD_SCHEDULE_ENABLE
.br
.
.B snapm
.de CMD_SCHEDULE_DISABLE
.  B schedule
.  B disable
.  IR schedule_name " "\c
..
.CMD_SCHEDULE_DISABLE
.br
.
.B snapm
.de CMD_SCHEDULE_LIST
.  B schedule
.  B list
.  ARGS_REPORT_OPTS
..
.CMD_SCHEDULE_LIST
.br
.
.B snapm
.de CMD_SCHEDULE_SHOW
.  B schedule
.  B show
.  IR schedule_name " "\c
.  RB [--json] " "\c
..
.CMD_SCHEDULE_SHOW
.br
.
.B snapm
.de CMD_SCHEDULE_GC
.  B schedule
.  B gc
.  RB -c | --config\ \c
.  IR schedule_name " "\c
..
.CMD_SCHEDULE_GC
.br
.PP
.
.SH DESCRIPTION
snapm is a \fIsnapshot manager\fP for Linux systems. It manages snapshots taken
at a common moment in time as a \fIsnapshot set\fP ("snapset").
.SH OPTIONS
.
.TP 8
.B -a | --autoindex
When creating snapshot sets treat \fBname\fP as a common basename and
generate and append a new, non-negative index value, to create a unique
instance name.
.IP
This is useful when creating recurring snapshot sets of the same set of
sources, for example to create a timeline of snapshots for recovery and
revert purposes.
.
.TP 8
.B -b | --bootable
When creating snapshot sets automatically create a snapshot boot entry
for the set.
.
.TP 8
\fB--cache-expires\fP \fIexpire_secs\fP
Specify diff cache expiry time in seconds (0 to disable expiry). The default
value is 900 seconds (15 minutes). This option is mutually exclusive with
\fB--cache-mode\fP.
.TP 8
\fB-C | --calendarspec\fP \fIcalendarspec\fP
Calendar event expression used to trigger scheduled creation of snapshot sets.
See \fBsystemd.time(7)\fP for the expression syntax.
.
.TP 8
\fB--color\fP \fImode\fP
(Diff) Enable colored output. Valid modes are \fBauto\fP, \fBnever\fP, and
\fBalways\fP.
.
.TP 8
\fB-c | --config\fP \fIschedule_name\fP
The name of a configured schedule.
.
.TP 8
.B -c | --content-only
(Diff) Only consider content changes when comparing file systems.
.
.TP 8
.B -C | --no-content-diff
(Diff) Do not generate content diffs for detected file modifications.
.
.TP 8
\fB-d | --debug\fP \fIdebug_flags\fP
A comma-separated list of subsystem names to enable debugging output
for, or 'all' to enable all debugging. The available debug classes
are: manager, command, report, schedule, mounts, fsdiff, plugin.
.
.TP 8
\fB-D | --desc\fP \fImode\fP
(Diff) Include change description in tree output. Valid modes are \fBnone\fP,
\fBshort\fP, and \fBfull\fP.
.
.TP 8
.B -f | --file-types
(Diff) Generate file type information using libmagic.
.
.TP 8
.B -F | --follow-symlinks
(Diff) Follow symbolic links when walking file system trees.
.
.TP 8
.B -h | --help
Display usage information and exit.
.
.TP 8
\fB-i | --include-pattern\fP \fIpattern\fP
(Diff) File patterns to include in comparison (glob notation).
.
.TP 8
.B --json
Produce output in JSON notation. See the JSON OUTPUT section.
.
.TP 8
\fB--keep-count\fP \fIcount\fP
Retain \fBcount\fP snapshot sets when applying the COUNT garbage
collection policy.
.
.TP 8
\fB--keep-years\fP \fIyears\fP
Retain \fByears\fP snapshot sets when applying the AGE garbage
collection policy.
.
.TP 8
\fB--keep-months\fP \fImonths\fP
Retain \fBmonths\fP snapshot sets when applying the AGE garbage
collection policy.
.
.TP 8
\fB--keep-weeks\fP \fIweeks\fP
Retain \fBweeks\fP snapshot sets when applying the AGE garbage
collection policy.
.
.TP 8
\fB--keep-days\fP \fIdays\fP
Retain \fBdays\fP snapshot sets when applying the AGE garbage
collection policy.
.
.TP 8
\fB--keep-yearly\fP \fIyearly\fP
Retain \fByearly\fP yearly snapshot sets when applying the
TIMELINE garbage collection policy.
.
.TP 8
\fB--keep-quarterly\fP \fIquarterly\fP
Retain \fBquarterly\fP quarterly snapshot sets when applying the
TIMELINE garbage collection policy.
.
.TP 8
\fB--keep-monthly\fP \fImonthly\fP
Retain \fBmonthly\fP monthly snapshot sets when applying the
TIMELINE garbage collection policy.
.
.TP 8
\fB--keep-weekly\fP \fIweekly\fP
Retain \fBweekly\fP weekly snapshot sets when applying the
TIMELINE garbage collection policy.
.
.TP 8
\fB--keep-daily\fP \fIdaily\fP
Retain \fBdaily\fP daily snapshot sets when applying the
TIMELINE garbage collection policy.
.
.TP 8
\fB--keep-hourly\fP \fIhourly\fP
Retain \fBhourly\fP hourly snapshot sets when applying the
TIMELINE garbage collection policy.
.
.TP 8
\fB-H | --max-hash-size\fP \fIsize\fP
(Diff) Maximum file size for generating content hashes (default: 1MiB).
.
.TP 8
\fB-m | --max-file-size\fP \fIsize\fP
(Diff) Maximum file size for comparisons (0=unlimited).
.
.TP 8
\fB-M | --cache-mode\fP \fIcache_mode\fP
Specify diff caching mode (\fIauto\fP, \fInever\fP, \fIalways\fP). The default
(\fIauto\fP) automatically expires the diff cache after 900 seconds (15
minutes).  Using \fIalways\fP disables cache expiry. To disable the use of the
cache entirely use \fInever\fP. This option is mutually exclusive with
\fB--cache-expires\fP.
.
.TP 8
.B --members
Include individual snapshots in the output of \fBsnapset show\fP commands.
.
.TP 8
\fB-n | --name\fP \fIname\fP
Specify a snapshot set name to operate on.
.
.TP 8
.B --name-prefixes | --nameprefixes
Add a 'SNAPM_' prefix plus the field name to the output. Useful with
\fB--noheadings\fP to produce a list of field=value pairs that can be used
to set environment or shell variables.
.
.TP 8
.B --no-headings | --noheadings
Suppress output of report headings.
.
.TP 8
\fB-o | --options\fP \fIfields\fP
Specify which fields to display.
.
.TP 8
\fB-o | --output-format\fP \fIformat\fP
(Diff) Output format for diff data. Valid formats are \fBpaths\fP, \fBfull\fP,
\fBshort\fP, \fBjson\fP, \fBdiff\fP, \fBsummary\fP, and \fBtree\fP. This option
may be specified multiple times to print different output formats for the same
run. The default if \fB--output-format\fP is not specified is \fBtree\fP.
.
.TP 8
\fB-O | --sort\fP \fIsort_fields\fP
Specify which fields to sort by.
.
.TP 8
\fB-s | --start-path\fP \fIpath\fP
(Diff) Start traversal from the specified path. This option may be specified
multiple times to traverse different subtrees in a single diff operation.
.
.TP 8
.B --stat
(Diff) Include diffstat output in \fBdiff\fP and \fBsummary\fP output.
.
.TP 8
.B -p | --ignore-permissions
(Diff) Ignore permissions when computing diffs.
.
.TP
\fB-p | --policy-type\fP \fIpolicy_type\fP
Select the garbage collection policy applied to snapshot sets created by a
schedule. Valid values are \fBALL\fP, \fBCOUNT\fP, \fBAGE\fP, and
\fBTIMELINE\fP.
.
.TP 8
.B -P | --pretty
(Diff) Pretty print output if supported by output format (e.g. JSON).
.
.TP 8
.B -q | --quiet
(Diff) Do not output progress or status information.
.
.TP 8
.B -r | --revert
When creating snapshot sets automatically create a snapshot revert entry
for the set.
.
.TP 8
.B --rows
Output report columns as rows.
.
.TP 8
\fB--separator\fP \fIseparator\fP
Report field separator.
.
.TP 8
\fB-s | --size-policy\fP \fIsize_policy\fP
Specify a default size policy when creating snapshot sets.
.
.TP 8
\fB-N | --snapshot-name\fP \fIname\fP
Specify a snapshot name to operate on.
.
.TP 8
\fB-U | --snapshot-uuid\fP \fIUUID\fP
Specify a snapshot UUID to operate on.
.
.TP 8
.B --start
Start the specified schedule immediately when enabling it with
\fBsnapm schedule enable\fP.
.
.TP 8
.B -t | --ignore-timestamps
(Diff) Ignore timestamps when computing diffs.
.
.TP 8
\fB-u | --uuid\fP \fIUUID\fP
Specify a snapshot set UUID to operate on.
.
.TP 8
.B -v | --verbose
Increase verbosity level. Specify multiple times, or set additional
debug classes with \fB--debug\fP to enable more verbose messages.
.
.TP 8
.B -V | --version
Display the version of \fBsnapm\fP and exit.
.TP 8
.B -w | --ignore-ownership
(Diff) Ignore ownership when computing diffs.
.
.TP 8
\fB-x | --exclude-pattern\fP \fIpattern\fP
(Diff) File patterns to exclude from comparison (glob notation).
.
.TP 8
\fB-z | --max-diff-size\fP \fIsize\fP
(Diff) Maximum file size for generating content diffs (default: 1MiB).
.
.SS Identifier arguments
Commands that accept an identifier may use either a positional
.I name
or
.I UUID ,
or the explicit options
.B -n | --name
and
.B -u | --uuid
(with snapshot variants
.B -N | --snapshot-name
and
.B -U | --snapshot-uuid ).
These forms are mutually exclusive. Mixing positional and explicit
arguments in the same invocation is a parse error; in this case the
command exits with status 2.
.SH SNAPSHOT SETS AND SNAPSHOTS
.
The \fBsnapm\fP command manages named collections of snapshots taken at a
common point in time as \fIsnapshot sets\fP. A snapshot set is created from a
list of sources (mount point or block device paths) and allows the state of the
system to be captured spanning over several volumes.
.P
Valid characters for snapshot set names are:
.BR a \(en z
.BR A \(en Z
.BR 0 \(en 9
.B + . -
.P
The underscore character ('_') is not permitted.
.P
Snapshot sets and snapshots are also identified by a unique UUID value.
.P
A plugin model is used to map mount points or devices onto possible snapshot
\fIproviders\fP. A provider plugin must exist for each source path specified
when creating a snapshot set. The current plugins support LVM2 copy-on-write,
LVM2 thin provisioned and Stratis snapshots.
.P
Plugins are assigned a positive integer priority value: in the case that two
or more plugins are able to snapshot the same source (for example,
\fBlvm2-cow\fP vs. \fBlvm2-thin\fP on the same logical volume, or file system
vs. block device snapshots), the plugin with the greater priority value is
selected automatically.
.P
Plugins have a default static priority value assigned by the plugin author.
System administrators can override this by modifying the appropriate file in
\fI/etc/snapm/plugins.d\fP. See \fBsnapm-plugins.d(5)\fP for further
information.
.P
The \fIsnapset\fP subcommand allows snapshot sets to be created, deleted,
enumerated, renamed, reverted, and activated or deactivated.
.P
The \fIsnapshot\fP subcommand provides access to information describing
individual snapshots that are part of a snapshot set, for example the device
path and snapshot status.
.
.P
.SS Snapshot set and snapshot status
.P
Snapshots from different providers may exist in several possible states:
\fIActive\fP, \fIInactive\fP, \fIInvalid\fP, or \fIReverting\fP.
.P
Some providers allow snapshots to be in an \fIActive\fP or \fIInactive\fP state
and snapshots for some providers (for example LVM2 Copy-on-Write snapshots)
have a specific size for the snapshot data store. If this space is completely
consumed the snapshot becomes \fIInvalid\fP and can no longer be accessed.
.P
When a revert is executed for a snapshot set that is currently mounted the
status of the snapshot set is \fIReverting\fP. If the snapshot set is in use
(either the origin or snapshot volumes are mounted) the revert will take place
the next time the volumes making up the snapshot set are activated and the
snapshot set status will remain \fIReverting\fP until the operation is
complete.
.P
The status of a snapshot set is an aggregation of the status of the individual
snapshots it contains: if any snapshots are \fIInvalid\fP then the overall
status of the snapshot set is also \fIInvalid\fP. If any snapshots within the
set are \fIReverting\fP then the snapshot set status as a whole is also
\fIReverting\fP. Finally, if any snapshots are \fIInactive\fP then the
status of the snapshot set is \fIInactive\fP.
.P
.B Snapshot size policies
.P
An optional size policy hint can be specified when creating a snapshot set,
either as a global default or individually for each source path. The policy is
used at creation time to check that sufficient space is present.
.IP
For snapshot providers that require a fixed space to be allocated for the
snapshot the policy is used to determine the size of the snapshot backing
store.
.IP
There are currently four types of size policy that can be used to specify the
space required:
.sp
.TP 8
.B FIXED
A fixed size with optional unit suffix (MiB, GiB, TiB, etc.).
.TP 8
.B %FREE
A percentage of the free space available from 0 to 100%.
.TP 8
.B %USED
A percentage of the space currently consumed on the mount point, as reported
by \fIdf\fP. Values greater than 100% can be used to allow the existing content
to be completely overwritten without running out of space. This policy can only
be applied to snapshot sources that correspond to mounted file systems.
.TP 8
.B %SIZE
A percentage of the size of the origin volume from 0 to 100%.
.
.P
.br
The default size policy for mounted volumes if none is specified is
\fB200%USED\fP.
The default size policy for unmounted block devices is \fB25%SIZE\fP.
.
.SH COMMANDS
.P
Snapshot manager commands consist of a \fBtype\fP (\fBsnapset\fP,
\fBsnapshot\fP, \fBplugin\fP, \fBschedule\fP), followed by a type-specific
subcommand.
.P
.B Snapshot Set Commands
.P
.
.TP
.B snapm
.CMD_SNAPSET_CREATE
.br
Create a new snapshot set using the specified list of mount points and block
devices.
.IP
The newly created snapshot set is displayed on the terminal on success:
.IP
.EX
# snapm snapset create backup / /home /var /opt /srv
SnapsetName:      backup
Sources:          /, /home, /var, /opt, /srv
NrSnapshots:      5
Time:             2024-12-05 17:46:12
UUID:             87c89914-51a5-5043-8513-667100213243
Status:           Inactive
Categories:       daily, hourly
Autoactivate:     no
Mounted:          no
Bootable:         no
.EE
When creating snapshot sets \fB--bootable\fP and \fB--revert\fP can optionally
be used to automatically create snapshot boot and revert boot entries
respectively.
.IP
A size policy can be specified on the create command line, either as a global
default or individually for each source path. To specify a default policy use
the \fB--size-policy\fP argument.  To specify a per-source path size policy
append the policy to the source path separated by the \fB:\fP character:
.IP
.EX
# snapm snapset create backup --size-policy 25%FREE /:4G /home /var
SnapsetName:      backup
Sources:          /, /home, /var
NrSnapshots:      3
Time:             2024-12-05 17:47:19
UUID:             4106d5b5-b521-504d-8822-8826594debb5
Status:           Inactive
Categories:       daily, hourly
Autoactivate:     no
Mounted:          no
Bootable:         no
.EE
.IP
Snapshot providers that do not allocate a fixed size for snapshot data will
check for available space according to the policy at creation time but do not
enforce a fixed size for individual snapshots: space is allocated from the
available pool on an as-needed basis.
.P
If the \fB--autoindex\fP argument is given the \fBname\fP given on the
command line is treated as a basename and a new, non-negative integer
index will be generated and appended to the \fBname\fP to construct a new,
unique instance name. This can be used to group a series of snapshot sets
of the same set of sources that are taken on a recurring schedule.
.IP
.EX
# snapm snapset create hourly --autoindex /:5%SIZE /var:5%SIZE
SnapsetName:      hourly.3
Sources:          /, /var
NrSnapshots:      2
Time:             2025-03-26 14:17:18
UUID:             ae082452-7995-5316-ac65-388eadd9879c
Status:           Active
Categories:       daily, hourly
Autoactivate:     yes
Mounted:          no
Bootable:         no
.EE
.
.TP
.B snapm
.CMD_SNAPSET_CREATE_SCHEDULED
.br
Create scheduled snapshot sets according to named configuration. This command
is normally called by the corresponding schedule timer. It may be issued
manually for testing or debugging purposes, or to create additional snapshot
sets not specified by the schedule parameters.
.
.TP
.B snapm
.CMD_SNAPSET_DELETE
.br
Delete the specified snapshot set. The snapshot set to delete may be specified
either by its \fBname\fP or \fBUUID\fP.
.
.TP
.B snapm
.CMD_SNAPSET_DIFF
.br
Compare two snapshot sets, or a snapshot set and the running system.
.IP
Calculates the differences between the \fBfrom\fP and \fBto\fP targets. Targets
may be specified as a snapshot set name, or the special character \fB.\fP to
represent the currently running system (root file system).
.IP
The output format is controlled by \fB--output-format\fP. The \fBtree\fP
format provides a hierarchical view of changes, while \fBdiff\fP provides
standard unified diff output for modified content: see \fBOutput Formats\fP for
a full description of the available formats. Multiple output formats may be
specified by repeating the \fB--output-format\fP argument with the required
formats. The default format if no \fB--output-format\fP is specified is
\fBtree\fP.
.IP
File comparisons can be tuned to ignore specific attributes (timestamps,
permissions, ownership) or to filter based on file patterns and sizes.
.IP
By default the results of diff computations are stored in an on-disk cache.
The default cache expiry time is 900 seconds (15 minutes). Cache behaviour can
be controlled with the \fB--cache-mode\fP and \fB--cache-expires\fP options.
.IP
.B Output Formats
paths, full, short, json, diff, summary, tree
.IP
The \fB--output-format\fP option accepts the following values:
.IP
.B \[bu] paths
A simple list of changed paths, one per line.
.IP
.B \[bu] full
Detailed change information including file attributes (mode, user, group, size,
time).
.IP
.B \[bu] short
Abbreviated change description (path, difference type and summary).
.IP
.B \[bu] json
Change data formatted as a JSON object.
.IP
.B \[bu] diff
Standard unified diff output of file content changes.
.IP
.B \[bu] summary
A brief summary of the count of different change types.
.IP
.B \[bu] tree
(Default) A hierarchical tree view of changes, using prefixes to indicate
status.
.IP
.B Tree Output Legend
.IP
The \fBtree\fP output format uses the following prefixes to indicate file status:
.IP
.B \[bu] [+]
Path added (green)
.IP
.B \[bu] [-]
Path removed (red)
.IP
.B \[bu] [*]
Path modified (yellow)
.IP
.B \[bu] [<]
Path moved from (cyan)
.IP
.B \[bu] [>]
Path moved to (cyan)
.IP
.B \[bu] [!]
Path file type changed (blue)
.
.TP
.B snapm
.CMD_SNAPSET_DIFFREPORT
.br
Compare snapshot sets and output results in a tabular report.
.IP
Performs the same comparison logic as \fBsnapm snapset diff\fP but formats
the output as a report using the standard reporting columns.
.IP
This command supports standard reporting arguments including \fB--options\fP,
\fB--sort\fP, \fB--noheadings\fP, and \fB--json\fP.
.TP
.B snapm
.CMD_SNAPSET_RENAME
.br
Rename an existing snapshot set. The snapshot set to be renamed is specified as
\fBold_name\fP and the new name is given as \fBnew_name\fP.
.
.TP
.B snapm
.CMD_SNAPSET_REVERT
.br
Revert an existing snapshot set, re-setting the content of the origin volumes
to the state they were in at the time the snapshot set was created. The
snapshot set to be reverted may be specified either by its \fBname\fP or
\fBUUID\fP.
.IP
Reverting a snapshot set with mounted and in-use origin volumes will schedule
the revert to take place the next time that the volumes are activated, for
example by booting into a configured revert boot entry for the snapshot set.
.
.TP
.B snapm
.CMD_SNAPSET_RESIZE
.br
Resize the members of an existing snapshot set, re-applying size policies to
one or more of the snapshots making up the set. The snapshot set to resize may
be specified by either its \fBname\fP or \fBUUID\fP.
.IP
For snapshot providers that require a fixed space to be allocated to the
snapshot this command will physically resize the corresponding snapshot
according to the given size policy (\fBlvm2-cow\fP). For snapshot providers
that dynamically allocate space the command will check that the requested
space is available at the time of the resize command. An error is returned if
the specified size policies cannot be satisfied.
.IP
Size policies may be specified on a per-source basis using the same syntax as
the \fBsnapset create\fP command. A default size policy can be set using the
\fB--size-policy\fP argument. If no source paths are specified the command
applies the default size policy to each member of the snapshot set.
.IP
The \fBlvm2-cow\fP plugin does not support shrinking snapshots, as this is
not supported by the LVM2 tools.
.
.TP
.B snapm
.CMD_SNAPSET_SPLIT
.br
Split snapshots from an existing snapshot set into a new snapshot set.
.IP
Split the snapshot set named \fBname\fP into a new snapshot set named
\&'\fBnew_name\fP'. Each listed source from '\fBname\fP' is split into the new
snapshot set. Sources that are not listed on the command line remain part of
the original snapshot set. It is an error to split \fIall\fP sources from a
snapshot set: in this case use '\fBsnapm snapset rename\fP' instead.
.
.TP
.B snapm
.CMD_SNAPSET_PRUNE
.br
Prune snapshots from an existing snapshot set.
.IP
Prune the listed sources from the snapshot set named \fBname\fP. The listed
snapshot sources are pruned from the snapshot set and permanently deleted.
This operation is irreversible.
.IP
It is an error to prune \fIall\fP sources from a snapshot set: in this case use
\&'\fBsnapm snapset delete\fP' instead.
.
.TP
.B snapm
.CMD_SNAPSET_ACTIVATE
.br
Attempt to activate snapshots making up snapshot sets. If no argument is given
the command will attempt to activate all snapshots of all snapshot sets present
on the system. If a \fBname\fP or \fBUUID\fP is specified then only that
snapshot set will be activated.
.IP
Not all snapshot providers support optional activation for snapshot volumes:
for these providers activate and deactivate have no effect on volume
availability.
.
.TP
.B snapm
.CMD_SNAPSET_DEACTIVATE
.br
Attempt to deactivate snapshots making up snapshot sets. If no argument is
given the command will attempt to deactivate all snapshots of all snapshot
sets present on the system. If a \fBname\fP or \fBUUID\fP is specified then
only that snapshot set will be deactivated.
.IP
Not all snapshot providers support optional activation for snapshot volumes:
for these providers activate and deactivate have no effect on volume
availability.
.
.TP
.B snapm
.CMD_SNAPSET_AUTOACTIVATE
.br
Enable or disable snapshot autoactivation for snapshot sets matching selection
criteria. Some snapshot providers (lvm2-thin) support optional snapshot volume
activation when activating resources for e.g. at boot time. The \fBsnapset
autoactivate\fP subcommand allows control of this behaviour for snapshot sets
managed by \fBsnapm\fP.
.
.TP
.B snapm
.CMD_SNAPSET_LIST
.br
Output a tabular report of snapshot sets.
.IP
Displays a report with one snapshot set per line, containing fields describing
the properties of the configured snapshot sets.
.IP
The list of fields to display is given with \fB-o|--options\fP as a comma
separated list of field names. To obtain a list of available fields run
\&'\fBsnapm snapset list -o help\fP'. If the list of fields begins with the
\&'\fB+\fP' character the specified fields are appended to the default field
list. Otherwise the given list of fields replaces the default set of report
fields.
.IP
The \fB--rows\fP, \fB--noheadings\fP, and \fB--nameprefixes\fP options can be
used to generate output in a machine readable form, suitable for setting shell
or environment variables.
.IP
Report output may be sorted by multiple user-defined keys using the \fB--sort\fP
option. The option expects a comma separated list of keys, with optional
\fB+\fP and \fB-\fP prefixes indicating ascending and descending sort for
that field respectively.
.
.TP
.B snapm
.CMD_SNAPSET_SHOW
.br
Display snapshot sets matching selection criteria on standard out. If the
\fB--members\fP option is given individual snapshots are included in the
output.
.
.TP
.B snapm
.CMD_SNAPSET_MOUNT
.br
Mount the members of the specified snapshot set. The root volume is mounted at
\fI/run/snapm/mounts/<name>\fP. Bind mounts for API and runtime file systems
are created automatically.
.
.TP
.B snapm
.CMD_SNAPSET_UMOUNT
.br
Unmount the specified snapshot set members from \fI/run/snapm/mounts/<name>\fP.
.
.TP
.B snapm
.CMD_SNAPSET_EXEC
.br
Execute the specified command in snapshot set \fIname\fP. Arguments following
\fIcommand\fP are passed through verbatim.
.
.TP
.B snapm
.CMD_SNAPSET_SHELL
.br
Start an interactive shell in snapshot set \fIname\fP.
.
.P
.B Snapshot Commands
.P
.
.TP
.B snapm
.CMD_SNAPSHOT_ACTIVATE
.br
Attempt to activate individual snapshots matching selection criteria. If no
argument is given the command will attempt to activate all snapshots of all
snapshot sets present on the system. If a snapshot or snapshot set \fBname\fP
or \fBUUID\fP is specified then only matching volumes will be activated.
.IP
Not all snapshot providers support optional activation for snapshot volumes:
for these providers activate and deactivate have no effect on volume
availability.
.
.TP
.B snapm
.CMD_SNAPSHOT_DEACTIVATE
.br
Attempt to deactivate individual snapshots matching selection criteria. If no
argument is given the command will attempt to deactivate all snapshots of all
snapshot sets present on the system. If a snapshot or snapshot set \fBname\fP
or \fBUUID\fP is specified then only matching volumes will be deactivated.
.P
Not all snapshot providers support optional activation for snapshot volumes:
for these providers activate and deactivate have no effect on volume
availability.
.
.TP
.B snapm
.CMD_SNAPSHOT_AUTOACTIVATE
.br
Enable or disable snapshot autoactivation for individual snapshots matching
selection criteria. Some snapshot providers (lvm2-thin) support optional
snapshot volume activation when activating resources for e.g. at boot time. The
\fBsnapshot autoactivate\fP subcommand allows control of this behaviour for
individual snapshots managed by \fBsnapm\fP.
.
.TP
.B snapm
.CMD_SNAPSHOT_LIST
.br
Output a tabular report of snapshots.
.IP
Displays a report with one snapshot per line, containing fields describing the
properties of the configured snapshots.
.IP
The list of fields to display is given with \fB--options\fP as a comma separated
list of field names. To obtain a list of available fields run '\fBsnapm snapshot
list -o help\fP'. If the list of fields begins with the '\fB+\fP' character the
specified fields are appended to the default field list. Otherwise the given
list of fields replaces the default set of report fields.
.IP
The \fB--rows\fP, \fB--noheadings\fP, and \fB--nameprefixes\fP options can be
used to generate output in a machine readable form, suitable for setting shell
or environment variables.
.IP
Report output may be sorted by multiple user-defined keys using the \fB--sort\fP
option. The option expects a comma separated list of keys, with optional
\fB+\fP and \fB-\fP prefixes indicating ascending and descending sort for
that field respectively.
.
.TP
.B snapm
.CMD_SNAPSHOT_SHOW
.br
Display snapshots matching selection criteria on standard out.
.
.P
.B Plugin Commands
.P
.
.TP
.B snapm
.CMD_PLUGIN_LIST
.br
Output a tabular report of plugins.
.P
Displays a report with one plugin per line, containing fields describing the
properties of the available plugins.
.P
The list of fields to display is given with \fB--options\fP as a comma separated
list of field names. To obtain a list of available fields run '\fBsnapm plugin
list -o help\fP'. If the list of fields begins with the '\fB+\fP' character the
specified fields are appended to the default field list. Otherwise the given
list of fields replaces the default set of report fields.
.P
The \fB--rows\fP, \fB--noheadings\fP, and \fB--nameprefixes\fP options can be
used to generate output in a machine readable form, suitable for setting shell
or environment variables.
.P
Report output may be sorted by multiple user-defined keys using the \fB--sort\fP
option. The option expects a comma separated list of keys, with optional
\fB+\fP and \fB-\fP prefixes indicating ascending and descending sort for
that field respectively.
.
.P
.B Schedule Commands
.P
.
.TP
.B snapm
.CMD_SCHEDULE_CREATE
.br
Create a new snapshot set schedule.
.IP
Create a persistent schedule to automatically create snapshot sets
according to the name and arguments given to the \fBsnapm schedule
create\fP command.
.IP
Scheduled snapshot sets are created with the \fIautoindex\fP argument enabled,
to ensure uniqueness of the created snapshot set names.
.IP
New snapshot sets will be automatically created as configured by the
specified calendar event expression (\fB--calendarspec\fP).
.IP
The \fBsnapm schedule create\fP command accepts the same set of
arguments as the \fBsnapm snapset create\fP command (with the exception of
\fB--autoindex\fP, which is always enabled for scheduled snapshot set creation)
and these are passed on to the snapshot sets created by the schedule.
.IP
A garbage collection policy specified by the \fB--policy-type\fP and
configured by the corresponding \fB--keep-*\fP arguments is applied to
automatically delete snapshot sets that are no longer required.
.IP
Newly created schedules are automatically enabled and will begin
creating snapshot sets at the first expiry of the configured calendar
expression.
.IP
.EX
# snapm schedule create --policy-type count --keep-count 2 --bootable \
--revert --size-policy 25%SIZE --calendarspec hourly hourly / /var
Name: hourly
Sources: /, /var
DefaultSizePolicy: 25%SIZE
Calendarspec: hourly
Boot: yes
Revert: yes
GcPolicy:
    Name: hourly
    Type: Count
    Params: keep_count=2
Enabled: yes
Running: yes
NextElapse: 2025-08-23 04:00:00
.EE
.
.TP
.B snapm
.CMD_SCHEDULE_DELETE
.br
Delete snapshot set schedule.
.IP
Delete an existing snapshot set schedule by name. The specified schedule
is disabled and removed from the system. Existing snapshot sets created
by the schedule before its deletion remain and continue to be available
until deleted by the user.
.
.TP
.B snapm
.CMD_SCHEDULE_EDIT
.br
Modify an existing snapshot set schedule.
.IP
Modify a persistent schedule to automatically create snapshot sets
according to the name and arguments given to the \fBsnapm schedule
edit\fP command. Arguments not specified on the \fBedit\fP command
line are taken from the existing schedule.
.IP
The \fBsnapm schedule edit\fP command accepts the same set of
arguments as the \fBsnapm schedule create\fP command.
.IP
If \fB-p policy_type\fP is provided without type-specific parameters, the
existing policy is retained (except for the \fBall\fP policy type, which has
no parameters and is applied directly).
.
.TP
.B snapm
.CMD_SCHEDULE_ENABLE
.br
Enable existing snapshot set schedule.
.IP
Enable an existing snapshot set schedule by name. The specified schedule
is enabled and will be started on subsequent reboots. To start the schedule
timer immediately use \fB--start\fP.
.
.TP
.B snapm
.CMD_SCHEDULE_DISABLE
.br
Disable existing snapshot set schedule.
.IP
Disable an existing snapshot set schedule by name. The specified
schedule is stopped and disabled, and will no longer automatically start
on subsequent reboots.
.
.TP
.B snapm
.CMD_SCHEDULE_LIST
.br
Output a tabular report of configured schedules.
.IP
Displays a report with one schedule per line, containing fields describing the
properties of the configured schedules.
.IP
The list of fields to display is given with \fB-o|--options\fP as a comma
separated list of field names. To obtain a list of available fields run
\&'\fBsnapm schedule list -o help\fP'. If the list of fields begins with the
\&'\fB+\fP' character the specified fields are appended to the default field
list. Otherwise the given list of fields replaces the default set of report
fields.
.IP
The \fB--rows\fP, \fB--noheadings\fP, and \fB--nameprefixes\fP options can be
used to generate output in a machine readable form, suitable for setting shell
or environment variables.
.IP
Report output may be sorted by multiple user-defined keys using the \fB--sort\fP
option. The option expects a comma separated list of keys, with optional
\fB+\fP and \fB-\fP prefixes indicating ascending and descending sort for
that field respectively.
.IP
.EX
# snapm schedule list
ScheduleName ScheduleSources SizePolicy OnCalendar Enabled NextElapse
daily        /, /var         10%SIZE    daily      yes     2025-08-25 00:00:00
.EE
.
.TP
.B snapm
.CMD_SCHEDULE_GC
.br
Run garbage collection for snapshot set schedule.
.IP
Run the configured garbage collection policy for the schedule specified with
\fB-c | --config\fP \fIschedule_name\fP.
.br
Cleans up snapshot sets created by \fIschedule_name\fP, applying the configured
cleanup policy and parameters given to \fBsnapm schedule create\fP.
.IP
The names of deleted snapshot sets are printed to standard output.
.SH SCHEDULING AND GARBAGE COLLECTION
Snapshot manager supports automatically creating snapshot sets according to a
user-defined schedule. A \fBgarbage collection policy\fP provides for
automatically cleaning up snapshot sets that are no longer required according
to a user defined policy and retention parameters.
.IP
Snapshot set schedules are created with the \fBsnapm schedule create\fP
command. The command accepts the same set of arguments as \fBsnapm snapset
create\fP allowing the properties of scheduled snapshot sets to be controlled
by the user.
.P
.B Garbage collection policies
.P
.sp
.TP 8
.B ALL
Retain all snapshot sets. This policy accepts no parameters and never deletes
snapshot sets automatically.
.TP 8
.B COUNT
Retain a fixed number of snapshot sets. This policy accepts a single parameter,
\fB--keep-count=count\fP and retains up to \fBcount\fP snapshot sets.
.TP 8
.B AGE
Retain snapshot sets younger than specified age. This policy accepts up to
four parameters (\fB--keep-years=years\fP, \fB--keep-months=months\fP,
\fB--keep-weeks=weeks\fP, \fB--keep-days=days\fP) and retains snapshot sets
that were created more recently than the specified age limit. The limit
applied is the sum of the parameters given.
.TP 8
.B TIMELINE
Retain snapshot sets according to classification. Each snapshot set is
classified as
.I hourly,
.I daily,
.I weekly,
.I monthly,
.I quarterly,
or
.I yearly
according to its creation time: the first snapshot set taken at the beginning
of each hour is classified as
.I hourly,
the first taken after midnight each day as
.I daily,
the first taken after midnight each Monday as
.I weekly,
and so on. A fixed number of snapshot sets is retained for each classification
according to the value of the
.B \-\-keep-hourly,
.B \-\-keep-daily,
.B \-\-keep-monthly,
.B \-\-keep-quarterly,
and
.B \-\-keep-yearly
parameters.
.SH BOOTING AND REVERTING SNAPSHOT SETS
.
Snapshot manager integrates with the \fBboom(8)\fP boot manager to facilitate
booting and reverting snapshot sets. Specifying the \fB-b|--bootable\fP or
\fB-r|--revert\fP arguments when creating a snapshot set will cause
\fBsnapm\fP to create a snapshot boot or revert boot entry respectively.
.P
The snapshot boot entry allows the system to boot into the state of the system
at the time the snapshot was created. This can be used to inspect the previous
state of the system or to quickly recover from a failed update or
reconfiguration.
.P
In order to reset the system back to the state at the time the snapshot set was
created the revert boot entry is used \fIafter\fP issuing a \fBsnapm snapset
revert\fP command. After running the \fBrevert\fP command the system should
be rebooted into the revert boot entry. This will start the revert
operation on all affected volumes.
.P
While the operation is in progress the snapshot set will appear with the
status of \fIReverting\fP.
.P
Reverting a snapshot set will also destroy the snapshot set since the snapshot
volumes are folded back into the origin devices. Following the completion of a
revert operation the snapshot set will no longer appear in the output of
\fBsnapm snapset list\fP or \fBsnapm snapset show\fP commands.
.
.SH REPORTING COMMANDS
.
Both the \fBsnapset list\fP and \fBsnapshot list\fP commands use a common
reporting system to display the results of the query. The selection of fields,
and the order in which they are displayed may be controlled to produce custom
report formats using the \fB\-o\fP/\fB\-\-options\fP argument. The report
output can also be optionally sorted by one or more field values using the
\fB\-O\fP/\fB\-\-sort\fP argument.
.P
To display the available fields for a given report type use the special field
name \fIhelp\fP:
.br
.EX
# snapm snapset list -o help
Snapshot set Fields
-------------------
  name           - Snapshot set name [str]
  uuid           - Snapshot set UUID [uuid]
  basename       - Snapshot set basename [str]
  index          - Snapshot set index [idx]
  timestamp      - Snapshot set creation time as a UNIX epoch value [num]
  time           - Snapshot set creation time [time]
  nr_snapshots   - Number of snapshots [num]
  sources        - Snapshot set sources [strlist]
  mountpoints    - Snapshot set mount points [strlist]
  devices        - Snapshot set devices [strlist]
  status         - Snapshot set status [str]
  autoactivate   - Autoactivation status [str]
  mounted        - SnapshotSet mount status [str]
  origin_mounted - SnapshotSet origin mount status [str]
  mount_root     - SnapshotSet mount root directory path [str]
  bootable       - Configured for snapshot boot [str]
  bootentry      - Snapshot set boot entry [sha]
  revertentry    - Snapshot set revert boot entry [sha]
  categories     - Snapshot set timeline categories [strlist]
.EE
.
.SH REPORT FIELDS
.
The \fBsnapm\fP reports provide several types of field that may be added to the
default field set for either snapshot set or snapshot reports, or used to
create custom reports.
.
.SS Snapshot sets
.
Snapshot set fields provide information about snapshot sets as a whole,
including the name, number of snapshots, mount points, status and UUID.
.TP 8
.B name
The name of this snapshot set.
.TP 8
.B uuid
The UUID of this snapshot set.
.TP 8
.B basename
The basename of this snapshot set.
.TP 8
.B index
The index of this snapshot set, or the special value '-' if this snapshot set
does not have recurring instances.
.TP 8
.B timestamp
The snapshot set creation time as a UNIX epoch value.
.TP 8
.B time
The snapshot set creation time as a human readable string.
.TP 8
.B nr_snapshots
The number of snapshots contained in this snapshot set.
.TP 8
.B sources
The list of sources (devices or mount points) contained in this snapshot set.
.TP 8
.B mountpoints
The list of mount points contained in this snapshot set.
.TP 8
.B devices
The list of block devices contained in this snapshot set.
.TP 8
.B status
The current status of this snapshot set. See the Snapshot set and snapshot
status section.
.TP 8
.B autoactivate
The autoactivation setting for this snapshot set.
.TP 8
.B mounted
The snapshot set mount status.
.TP 8
.B origin_mounted
The snapshot set origin mount status.
.TP 8
.B mount_root
The path to the root volume mount if this snapshot set is currently mounted.
.TP 8
.B bootentry
The \fBboot identifier\fP of the boot loader entry configured to boot this
snapshot set, or the empty string if no boot entry has been created.
.TP 8
.B revertentry
The \fBboot identifier\fP of the boot loader entry configured to revert
this snapshot set following a merge operation, or the empty string if no
revert boot entry has been created.
.TP
.B categories
The timeline categories that this snapshot set belongs to: a list of strings
from the set "yearly", "quarterly", "monthly", "weekly", "daily", "hourly".
See the documentation for the \fItimeline\fP garbage collection policy for
more information on timeline categories.
.
.SS Snapshots
.
Snapshot fields provide information about the snapshots that make up snapshot
sets, including the fields available in the snapshot set report as well as
fields specific to individual snapshots.
.TP 8
.B snapshot_name
The provider-specific name used to refer to the snapshot.
.TP 8
.B snapshot_uuid
The snapshot UUID.
.TP 8
.B origin
The origin volume that this snapshot refers to.
.TP 8
.B mountpoint
The path to the mount point where this snapshot was taken from.
.TP 8
.B devpath
The provider-specific path to the device used to mount this snapshot.
.TP 8
.B provider
A string representing the snapshot provider plugin used to create this
snapshot.
.TP 8
.B status
The current status of this snapshot. See the Snapshot set and snapshot
status section.
.TP 8
.B size
The size of the snapshot as a human readable string.
.TP 8
.B free
The amount of free space available to the snapshot as a human readable string.
.TP 8
.B size_bytes
The size of the snapshot in bytes.
.TP 8
.B free_bytes
The amount of free space available to the snapshot in bytes.
.TP 8
.B autoactivate
Whether this snapshot is configured for autoactivation.
.P
.
.SS Plugins
.
.TP 8
.B name
Name of the plugin.
.TP 8
.B version
Version of the plugin.
.TP 8
.B type
The snapshot type created by this plugin.
.
.SS Schedules
.
Schedule fields provide access to information on configured schedules and the
recurring snapshot sets they create.
.TP
.B name
Name of the schedule.
.TP
.B sources
Schedule sources.
.TP
.B sizepolicy
Schedule default size policy.
.TP
.B autoindex
Schedule autoindex.
.TP
.B gcpolicytype
Schedule garbage collection policy type.
.TP
.B gcpolicyparams
Schedule garbage collection policy parameters.
.TP
.B oncalendar
Schedule OnCalendar trigger expression.
.TP
.B nextelapse
Time of next elapse.
.TP
.B enabled
Schedule enabled.
.TP
.B running
Schedule running.
.
.
.SH JSON OUTPUT
.
All reporting commands can optionally generate output in JSON notation by
using the \fB--json\fP argument. The output is a JSON object containing a
key for the object type (\fISnapsets\fP, \fISnapshots\fP, \fIPlugins\fP, or
\fISchedules\fP) that contains a JSON array of objects of the specified type.
.P
Reporting commands use JSON key names derived from the report field names. For
\fIlist\fP reports the JSON keys are always prefixed with the object type to
avoid collisions (e.g., \fIsnapset_name\fP). The \fB-o\fP/\fB--options\fP and
\fB-O\fP/\fB--sort\fP arguments accept those report field names (prefixes are
optional unless required to disambiguate).
.P
Selection and sorting is controlled with \fB--options\fP and \fB--sort\fP as
usual:
.P
.EX
# snapm snapset list --json -o+snapset_uuid --sort snapset_time
{
    "Snapsets": [
        {
            "snapset_name": "before-upgrade",
            "snapset_time": "2025-09-08 18:43:57",
            "snapset_nr_snapshots": 2,
            "snapset_status": "Active",
            "snapset_sources": [
                "/",
                "/var"
            ],
            "snapset_uuid": "6330328b-a9d0-5b41-ac96-53b371449965"
        },
        {
            "snapset_name": "backup",
            "snapset_time": "2025-09-09 17:12:21",
            "snapset_nr_snapshots": 3,
            "snapset_status": "Inactive",
            "snapset_sources": [
                "/",
                "/home",
                "/var"
            ],
            "snapset_uuid": "efa8a09d-cf9c-500b-ad68-32c4a0e159b4"
        }
    ]
}
.EE
.PP
The \fBcreate\fP, \fBcreate-scheduled\fP, and \fBshow\fP subcommands also
support optional JSON notation using the \fB--json\fP argument. This includes
the \fBsnapset\fP, \fBsnapshot\fP, and \fBschedule\fP \fBshow\fP subcommands:
.PP
.EX
# snapm snapset show --json before-upgrade
[
    {
        "SnapsetName": "before-upgrade",
        "Sources": [
            "/",
            "/home",
            "/var"
       ],
        "MountPoints": [
            "/",
            "/home",
            "/var"
        ],
        "Devices": [],
        "NrSnapshots": 3,
        "Timestamp": 1755915019,
        "Time": "2025-08-23 03:10:19",
        "UUID": "d9b63a58-333b-517a-b38d-7cc818040fab",
        "Status": "Active",
        "Categories": [
            "yearly",
            "monthly",
            "daily",
            "hourly"
        ],
        "Autoactivate": true,
        "Bootable": true,
        "BootEntries": {
            "SnapshotEntry": "61cb664",
            "RevertEntry": "74c1cf2"
        }
    }
]
.EE
.P
The JSON format produced by the \fBcreate\fP and \fBshow\fP commands uses JSON
key names that reflect the property names used in the normal \fBshow\fP
command output. The output is a JSON array containing objects of the specified
type.
.P
When boot entries are defined for a snapshot set the resulting JSON will
include a \fIBootEntries\fP object giving the corresponding \fBboom\fP
\fIboot_id\fP values.
.P
The \fBcreate\fP commands output a single JSON object of the corresponding
type. The \fBshow\fP commands produce a JSON array containing the selected
objects.
.SH EXAMPLES
List the available snapshot sets
.br
.
.EX
# snapm snapset list
SnapsetName  Time                 NrSnapshots Status   Sources
backup       2024-12-05 17:53:10            4 Active   /, /opt, /srv, /var
userdata     2024-12-05 17:53:22            2 Inactive /data, /home
.EE
.P
List the available snapshots
.br
.EX
# snapm snapshot list
SnapsetName  Name                                          Origin              Source  Status   Size     Free     Autoactivate Provider
backup       fedora/root-snapset_backup_1733421190_-       /dev/fedora/root    /       Active     8.8GiB   8.8GiB yes          lvm2-cow
backup       fedora/var-snapset_backup_1733421190_-var     /dev/fedora/var     /var    Active     6.4GiB   6.4GiB yes          lvm2-cow
backup       p1/fs2-snapset_backup_1733421190_-srv         /dev/stratis/p1/fs2 /srv    Active     2.0GiB   3.2GiB yes          stratis
backup       p1/fs1-snapset_backup_1733421190_-opt         /dev/stratis/p1/fs1 /opt    Active     1.0GiB   3.2GiB yes          stratis
.EE
.P
List the available snapshots, displaying the basename and index for each
.br
.
.EX
# snapm snapset list -o+basename,index
SnapsetName  Time                 NrSnapshots Status  Sources  Basename     Index
backup       2025-03-25 18:12:54            2 Invalid /, /var  backup           -
hourly.0     2025-03-26 14:00:00            2 Invalid /, /var  hourly           0
hourly.1     2025-03-26 15:00:00            2 Active  /, /var  hourly           1
hourly.2     2025-03-26 16:00:00            2 Active  /, /var  hourly           2
hourly.3     2025-03-26 17:00:00            2 Active  /, /var  hourly           3
.EE
.P
Create a new snapshot set from the mount points /, /home, and /var
.br
.
.EX
# snapm snapset create backup / /home /var
SnapsetName:      backup
Sources:          /, /home, /var
NrSnapshots:      3
Time:             2024-12-05 17:57:05
UUID:             b9b4cd96-75a5-5826-a26b-b617c06bd877
Status:           Active
Categories:       daily, hourly
Autoactivate:     no
Mounted:          no
Bootable:         no
.EE
.P
Create a bootable snapshot set from the mount points /, /home, and /var
.br
.
.EX
# snapm snapset create -br before-upgrade / /home /var
SnapsetName:      before-upgrade
Sources:          /, /home, /var
NrSnapshots:      3
Time:             2025-08-23 03:10:19
UUID:             d9b63a58-333b-517a-b38d-7cc818040fab
Status:           Active
Categories:       daily, hourly
Autoactivate:     yes
Mounted:          no
Bootable:         yes
BootEntries:
  SnapshotEntry:  61cb664
  RevertEntry:    74c1cf2
.EE
.P
Create a bootable snapshot set from the mount points /, /home, and /var,
with output formatted in JSON notation
.br
.EX
# snapm snapset create -br --json before-upgrade / /home /var
{
    "SnapsetName": "before-upgrade",
    "Sources": [
        "/",
        "/home",
        "/var"
    ],
    "MountPoints": [
        "/",
        "/home",
        "/var"
    ],
    "Devices": [],
    "NrSnapshots": 3,
    "Timestamp": 1755915019,
    "Time": "2025-08-23 03:10:19",
    "UUID": "d9b63a58-333b-517a-b38d-7cc818040fab",
    "Status": "Active",
    "Categories": [
        "daily",
        "hourly"
    ],
    "Autoactivate": true,
    "Mounted": false,
    "Bootable": true,
    "BootEntries": {
        "SnapshotEntry": "61cb664",
        "RevertEntry": "74c1cf2"
    }
}
.EE
.P
Delete the snapshot set named 'backup'
.br
.EX
# snapm snapset delete backup
.EE
Activate all snapshot sets with verbose output
.br
.
.EX
# snapm -v snapset activate
INFO - Activated 2 snapshot sets
.EE
.P
Rename the snapshot set 'backup' to 'oldbackup'
.br
.EX
# snapm snapset rename backup oldbackup
.EE
.P
Display the snapshot set named 'before-upgrade'
.br
.
.EX
# snapm snapset show before-upgrade
SnapsetName:      before-upgrade
Sources:          /, /home, /var
NrSnapshots:      3
Time:             2025-08-23 03:10:19
UUID:             d9b63a58-333b-517a-b38d-7cc818040fab
Status:           Active
Categories:       daily, hourly
Autoactivate:     yes
Mounted:          no
Bootable:         yes
BootEntries:
  SnapshotEntry:  61cb664
  RevertEntry:    74c1cf2
.EE
.P
Display the snapshot with UUID b201bdba-89b7-5014-a80d-f5d4b9a690ed
.br
.
.EX
# snapm snapshot show -U b201bdba-89b7-5014-a80d-f5d4b9a690ed
Name:           fedora/home-snapset_before-upgrade_1755915019_-home
SnapsetName:    before-upgrade
Origin:         /dev/fedora/home
Time:           2025-08-23 03:10:19
Source:         /home
MountPoint:     /home
Provider:       lvm2-thin
UUID:           b201bdba-89b7-5014-a80d-f5d4b9a690ed
Status:         Active
Size:           1.0GiB
Free:           1.9GiB
Autoactivate:   yes
DevicePath:     /dev/fedora/home-snapset_before-upgrade_1755915019_-home
VolumeGroup:    fedora
LogicalVolume:  home-snapset_before-upgrade_1755915019_-home
.EE
.P
.P
Compare the snapshot set 'backup' to the running system, displaying a tree view
.br
.EX
# snapm snapset diff --output-format tree backup .
.EE
.P
Show content differences between two snapshot sets, ignoring timestamps
.br
.EX
# snapm snapset diff --output-format diff --ignore-timestamps weekly.1 weekly.2
.EE
.P
Generate a JSON diff report between 'backup' and 'restore_point'
.br
.EX
# snapm snapset diffreport --json backup restore_point
.EE
.P
.SH EXIT STATUS
\fBsnapm\fP exits with one of the following status codes:
.TP 8
0
Command completed successfully.
.TP 8
.B 1
A runtime error occurred.
.TP 8
.B 2
Invalid arguments or option parsing error.
.SH FILES
Configuration is read from the following locations:
.PP
.
.I /etc/snapm/snapm.conf
.br
.I /etc/snapm/plugins.d
.br
.I /etc/snapm/schedule.d
.br
.PP
The main configuration file is \fI/etc/snapm/snapm.conf\fP.
Plugin-specific settings are stored in \fIplugins.d\fP, and snapshot schedules
are defined in \fIschedule.d\fP.
.PP
Snapshot set mounts are created in:
.PP
.I /run/snapm/mounts
.br
.PP
The snapshot set root volume is mounted to a directory named for the snapshot
set.
.
.SH BUGS
Please report bugs via the GitHub issue tracker:
.P
.UR https://\:github.com/snapshotmanager/snapm/issues
.UE
.
.SH AUTHORS
.
Bryn M. Reeves <bmr@redhat.com>
.
.SH SEE ALSO
.
.P
.BR snapm.conf (5).
.BR snapm-plugins.d (5).
.BR snapm-schedule.d (5).
.BR systemd.time (7).
.BR boom (8).
.BR lvm (8).
.BR stratis (8).
.br
.UR https://\:github.com/snapshotmanager/snapm
snapm project page
.UE
.br
.UR https://\:snapm.readthedocs.io/en/latest/user_guide.html
snapm user guide
.UE
.br
.UR https://\:snapm.readthedocs.io/en/latest/snapm.html
snapm API documentation
.UE
.br
.UR https://\:github.com/snapshotmanager/boom
Boom project page
.UE
.br
.UR https://\:www.sourceware.org/lvm2/
LVM2 resource page
.UE
.br
.UR https://\:stratis-storage.github.io/
Stratis resource page
.UE
.br
