FROM fedora:latest

RUN dnf -y install systemd dbus python3 python3-pip python3-virtualenv python3-pytest python3-coverage iproute iputils
RUN dnf -y builddep snapm
RUN dnf clean all

RUN mkdir -p /etc/snapm/schedule.d

COPY snapm-create@.service snapm-create@.timer snapm-gc@.service snapm-gc@.timer /usr/lib/systemd/system/
COPY snapm.conf /usr/lib/tmpfiles.d/

STOPSIGNAL SIGRTMIN+3

CMD /usr/sbin/init
